In [42]:
import numpy as np

# 数组元素的常见属性
a = np.arange(24)
print(f'数组的维数，即数组的秩: {a.ndim}')
print(f'数组的维度信息: {a.shape}') 
print(f'数组元素总个数: {a.size}')
print(f'数组元素的类型: {a.dtype}')
print(f'数组元素的占用字节大小: {a.itemsize}')
print('==========================================')


数组的维数，即数组的秩: 1
数组的维度信息: (24,)
数组元素总个数: 24
数组元素的类型: int32
数组元素的占用字节大小: 4
数组的维数，即数组的秩: 3
数组的维度信息: (2, 4, 3)


In [52]:
# 改变数组元素的数据类型

# from int to float
arr = np.array([1, 2, 3, 4, 5])
print(arr.dtype)  # default dtype is int32
float_arr = arr.astype(np.float64)  # int32 to float64
print(float_arr.dtype)

# from float to int
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
print(arr.astype(np.int32))  # decimal part was truncated

# from strings srepresenting numbers to numeric form
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype = np.string_)
print(numeric_strings.astype(np.float64))

int32
float64
[ 3 -1 -2  0 12 10]
[ 1.25 -9.6  42.  ]


In [34]:
# 新创建数组元素

# np.empty: Return a new array of given shape and type, without initializing entries.
x = np.empty([3,2], dtype = int)  # shape:（3， 2），default value is random
print (x.dtype, x)
print('----------------------------------------------')

# np.zeros： Return a new array of given shape and type, filled with zeros.
# similar functions: ones
x = np.zeros(5)  # default type is numpy.float64
print(x.dtype, x)
y = np.zeros((5,), dtype = np.int) 
print(y.dtype, y)
z = np.zeros((2,2), dtype = [('x', 'i4'), ('y', 'i4')]) # 自定义类型
print(z.dtype, z)
print('----------------------------------------------')

# np.full: Return a new array of given shape and type, filled with fill_value.
x = np.full((2,2), 10)
print(x)
print('----------------------------------------------')

# np.zeros_like: Return an array of zeros with the same shape and type as a given array.
# empty_like: Return an empty array with shape and type of input.
# ones_like: Return an array of ones with shape and type of input.
# full_like: Return a new array with shape of input filled with value.

x = np.zeros_like(5)  # default type is numpy.int32, same as ones_like
print(x.dtype, x)
y = np.zeros_like((5,), dtype = np.int) 
print(y.dtype, y)
z = np.zeros_like((2,2), dtype = [('x', 'i4'), ('y', 'i4')]) # 自定义类型
print(z.dtype, z)

int32 [[          0           0]
 [ -748610448         597]
 [          0 -2147483648]]
----------------------------------------------
float64 [0. 0. 0. 0. 0.]
int32 [0 0 0 0 0]
[('x', '<i4'), ('y', '<i4')] [[(0, 0) (0, 0)]
 [(0, 0) (0, 0)]]
----------------------------------------------
[[10 10]
 [10 10]]
int32 0
int32 [0]
[('x', '<i4'), ('y', '<i4')] [(0, 0) (0, 0)]


In [40]:
# 从已有数据创建数组

x = [1, 2, 3]
y = (1, 2, 3)
z = [(1,2,3),(4,5)] 
a = np.array(x)
b = np.array(y)
c = np.array(z)
print(a, b, c)
print(type(a), type(b), type(c))
a = np.asarray(x)
b = np.asarray(y)
c = np.asarray(z)
print(a, b, c)
print(type(a), type(b), type(c))

[1 2 3] [1. 2. 3.] [(1, 2, 3) (4, 5)]
<class 'numpy.ndarray'> <class 'numpy.ndarray'> <class 'numpy.ndarray'>
[1 2 3] [1 2 3] [(1, 2, 3) (4, 5)]
<class 'numpy.ndarray'> <class 'numpy.ndarray'> <class 'numpy.ndarray'>


In [62]:
# 以流的形式读入数据，创建新数组
# help(np.frombuffer)

# 从字符串读入数组
s = b'Hello World'  # buffer 是字符串的时候，Python3 默认 str 是 Unicode 类型，所以要转成 bytestring 在原 str 前加上 b
a = np.frombuffer(s, dtype = 'S1')
print(a)

b = np.frombuffer(s, dtype='S1', count=5, offset=1)
print(b)


[b'H' b'e' b'l' b'l' b'o' b' ' b'W' b'o' b'r' b'l' b'd']
[b'e' b'l' b'l' b'o' b' ']


In [100]:
# 从数值范围创建数组
# help(np.arange)

x = np.arange(5)
y = np.arange(10, 20 ,2)
print(x)
print(y)
print('-----------------------------')

# 创建一个由等差数列构成的一维数组
# help(np.linspace)
a = np.linspace(1, 10, 10)  # 起始值为1， 终止值为10， 数列个数为10
print(a) 
a = np.linspace(1, 10, 10, retstep=True)  # 显示步长
print(a)
a = np.linspace(1, 20, 191, retstep=True) 
# 步长的计算：(20-1)/(191-1)
print(b)
a = np.linspace(1, 10, 10, endpoint=False)  # 不包含终止值
print(a)
print('-----------------------------------')

[0 1 2 3 4]
[10 12 14 16 18]
-----------------------------
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
(array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), 1.0)
(array([ 1. ,  1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,
        2.1,  2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,
        3.2,  3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,
        4.3,  4.4,  4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,
        5.4,  5.5,  5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,
        6.5,  6.6,  6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.5,
        7.6,  7.7,  7.8,  7.9,  8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,
        8.7,  8.8,  8.9,  9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,
        9.8,  9.9, 10. , 10.1, 10.2, 10.3, 10.4, 10.5, 10.6, 10.7, 10.8,
       10.9, 11. , 11.1, 11.2, 11.3, 11.4, 11.5, 11.6, 11.7, 11.8, 11.9,
       12. , 12.1, 12.2, 12.3, 12.4, 12.5, 12.6, 12.7, 12.8, 12.9, 13. ,
       13.1, 13.2, 13.3, 13.4,

In [103]:
# 创建一个由等差比数列构成的一维数组
# logspace(start, stop, num=50, endpoint=True, base=10.0, dtype=None)
# 序列起始值: base**start
# 序列终止值: base**stop
# 取对数时，log的下标
a = np.logspace(1.0, 2.0, num=10)
print(a)
a = np.logspace(0, 9, 10, base=2)  # 将取对数的时候，log的下标由默认值10变为2
print(a)

[ 10.          12.91549665  16.68100537  21.5443469   27.82559402
  35.93813664  46.41588834  59.94842503  77.42636827 100.        ]
[  1.   2.   4.   8.  16.  32.  64. 128. 256. 512.]
[1.e+01 1.e+02 1.e+03 1.e+04 1.e+05 1.e+06 1.e+07 1.e+08 1.e+09 1.e+10
 1.e+11 1.e+12 1.e+13 1.e+14 1.e+15 1.e+16 1.e+17 1.e+18 1.e+19 1.e+20]


In [128]:
# 数组的切片 

# 一维数组
a = np.arange(10)
s = slice(2, 7, 2)
print(a[s])
print(a[2:7:2])
print("-----------------")

# 多维数组
a = np.array([[1,2,3],[3,4,5],[4,5,6]])
print(a)
print(a[2,2])
print(a[2,2])
print(a[1:])  # 第2，3行数据
print(a[:2])  # 取前2行数据
print(a[...,1])   # 第2列元素
print(a[...,1] == a[:, 1])
print(a[1,...])   # 第2行元素
print(a[...,1:])  # 第2列及剩下的所有元素
print(a[:2, 1:]) # 多个切片，取前2行的第1列后的数据

print('----------------')
# 数组切片是原始数组的视图。这意味着数据不会被复制，视
# 图上的任何修改都会直接反映到源数组上。
b = a[...,1:]
b[:] = 0
print(a)
c = a[..., 1:].copy() # 使用copy方法可以传递复制的数组对象
c[:] = 1
print(a)

[2 4 6]
[2 4 6]
-----------------
[[1 2 3]
 [3 4 5]
 [4 5 6]]
6
6
[[3 4 5]
 [4 5 6]]
[[1 2 3]
 [3 4 5]]
[2 4 5]
[ True  True  True]
[3 4 5]
[[2 3]
 [4 5]
 [5 6]]
[[2 3]
 [4 5]]
----------------
[[1 0 0]
 [3 0 0]
 [4 0 0]]
[[1 0 0]
 [3 0 0]
 [4 0 0]]


In [137]:
# 布尔型索引
# 通过布尔型索引选取数组中的数据，将总是创建数据的副本，即使返回一模一样的数组也是如此。

names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
names == 'Bob' 
print(data)
print('----------------')
print(data[names == 'Bob'])  #  筛选出names中等于'Bob'的元素
print(data[~(names == 'Bob')])  #  用~ 或者 != 反转条件

print('----------------')
data[data < 0] = 0   # 利用布尔型索引对数组中的数据赋值
print(data)
data[names != 'Joe'] = 7
print(data)

[[-0.61320721  1.28963858 -0.32948188 -1.52886162]
 [ 0.10640482  0.73673022 -0.46532478  0.89463231]
 [-0.54977783 -1.00271423 -0.73690536 -0.70319176]
 [-0.69923779  0.50090788  0.60464217 -0.10811821]
 [-0.28664286  0.75127237 -1.19579396  0.82060135]
 [-0.20242193 -0.21179038 -1.36273035  0.51545939]
 [ 0.94961831  0.22313998  0.62802133 -1.58001794]]
----------------
[[-0.61320721  1.28963858 -0.32948188 -1.52886162]
 [-0.69923779  0.50090788  0.60464217 -0.10811821]]
[[ 0.10640482  0.73673022 -0.46532478  0.89463231]
 [-0.54977783 -1.00271423 -0.73690536 -0.70319176]
 [-0.28664286  0.75127237 -1.19579396  0.82060135]
 [-0.20242193 -0.21179038 -1.36273035  0.51545939]
 [ 0.94961831  0.22313998  0.62802133 -1.58001794]]
----------------
[[0.         1.28963858 0.         0.        ]
 [0.10640482 0.73673022 0.         0.89463231]
 [0.         0.         0.         0.        ]
 [0.         0.50090788 0.60464217 0.        ]
 [0.         0.75127237 0.         0.82060135]
 [0.         0

In [55]:
# 数组的重塑

arr = np.arange(8)
print(arr)
b = arr.reshape((4,2))  # 返回新的数组，维度为（4，2）
print(b)
c = b.reshape((1, 2, -1))  # -1表示这个值由数组本身来推断
print(c)
print(c.shape)
d = c.ravel()  # 将数组扁平化为1维
e = c.flatten() # same as ravel()
print(d)
print(e)

[0 1 2 3 4 5 6 7]
[[0 1]
 [2 3]
 [4 5]
 [6 7]]
[[[0 1 2 3]
  [4 5 6 7]]]
(1, 2, 4)
[0 1 2 3 4 5 6 7]
[0 1 2 3 4 5 6 7]


In [29]:
# numpy的高级索引

# 整数数组索引， 总是返回新数组
x = np.array([[1,2], [3, 4], [5, 6]])
print(x)
y = x[[0,1,2], [0,1,0]]  # 选取数组中(0, 0), (1, 1), (2, 0)位置处的元素
print(y)  # 输出一个一维的数组

x = np.array([i*2 for i in range(20)])
y = x[[0, 2, 4, 8]]  # 索引为一个一维列表，获取数组下标为0，2，4，8的元素
print(y)
print('-------------------')


# 获取一个4×3数组中四个角的元素,行索引是 [0,0] 和 [3,3]，而列索引是 [0,2] 和 [0,2]
x = np.array([[0,  1,  2], [3,  4,  5], [6,  7,  8], [9,  10,  11]])
print(x)
rows = np.array([[0,3], [3, 3]])
cols = np.array([[0, 2], [0, 2]])
y = x[rows, cols]
print(f'此数组中四个角的元素为：\n{y}')
print('-------------------')


# 组合索引,返回一个视图
a = np.array([[1,2,3], [4,5,6],[7,8,9]])
b = a[1:3, 1:3]
c = a[1:3,[1,2]]
d = a[...,1:]
print(a)
print(b)
print(c)
print(d)
d[:] = 0  # 将d中元素全部置0
print(d)
print(a)


[[1 2]
 [3 4]
 [5 6]]
[1 4 5]
[ 0  4  8 16]
-------------------
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
此数组中四个角的元素为：
[[ 0 11]
 [ 9 11]]
-------------------
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[5 6]
 [8 9]]
[[5 6]
 [8 9]]
[[2 3]
 [5 6]
 [8 9]]
<class 'numpy.ndarray'>
[[0 0]
 [0 0]
 [0 0]]
[[1 0 0]
 [4 0 0]
 [7 0 0]]


In [38]:
# 花式索引

# 花式索引，指的是利用整数数组进行索引
# 无论原数组为几维，返回的总是一维数组
# 与切片不同，总会将数组元素复制到新的数组

arr = np.empty((8,4))
for i in range(8):
    arr[i] = i
print(arr)
print('------------------------')
b = arr[[4, 3, 0, 6]]  # 按照列表内元素的顺序，选择下标为4，3，0，6的行
print(b)
print('------------------------')
c = arr[[-3, -5, -7]]  # 利用负数索引选取
print(c)
print('------------------------')

arr = np.arange(32).reshape(8, 4)  # 利用多维整数数组进行索引
print(arr, '\n')
b = arr[[1, 5, 7, 2], [0, 3, 1, 2]]  # 返回一维数组，元素为(1,0), (5, 3), (7, 1), (2, 2)
print(b, '\n')
c = arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]  
print(c, '\n')
c[:] = 0
print(c, '\n')
print(arr)


[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]
 [5. 5. 5. 5.]
 [6. 6. 6. 6.]
 [7. 7. 7. 7.]]
------------------------
[[4. 4. 4. 4.]
 [3. 3. 3. 3.]
 [0. 0. 0. 0.]
 [6. 6. 6. 6.]]
------------------------
[[5. 5. 5. 5.]
 [3. 3. 3. 3.]
 [1. 1. 1. 1.]]
------------------------
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]] 

[ 4 23 29 10] 

[[ 4  7  5  6]
 [20 23 21 22]
 [28 31 29 30]
 [ 8 11  9 10]] 

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]] 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


In [47]:
# 数组的切片与整数数组索引的区别

arr = np.arange(32).reshape(8, 4)
print(arr)
print('\n')
b = arr[1:5, :2]  # 返回切片
print(b)
print('\n')
c = arr[[1, 5, 7, 2]]  # 返回新数组
print(c)
print('\n')

b[:] = 0
print(arr)  # 行、列式索引影响原数组
print('\n')

c[:] = 1
print(arr)  # 整数数组索引不影响原数组


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


[[ 4  5]
 [ 8  9]
 [12 13]
 [16 17]]


[[ 4  5  6  7]
 [20 21 22 23]
 [28 29 30 31]
 [ 8  9 10 11]]


[[ 0  1  2  3]
 [ 0  0  6  7]
 [ 0  0 10 11]
 [ 0  0 14 15]
 [ 0  0 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


[[ 0  1  2  3]
 [ 0  0  6  7]
 [ 0  0 10 11]
 [ 0  0 14 15]
 [ 0  0 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
