In [4]:
import numpy as np 

a = np.arange(9) 
print ('第一个数组：') 
print (a) 
print ('\n') 
print ('将数组分为三个大小相等的子数组：') 
b = np.split(a,3) 
print (b) 
print ('\n') 
print ('将数组在一维数组中表明的位置分割：') 
b = np.split(a,[4,7]) 
print(b)

第一个数组：
[0 1 2 3 4 5 6 7 8]


将数组分为三个大小相等的子数组：
[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]


将数组在一维数组中表明的位置分割：
[array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8])]


In [8]:
import numpy as np 

harr = np.floor(10 * np.random.random((2, 6))) 
print ('原 array：') 
print(harr) 
print ('拆分后：') 
b = np.hsplit(harr, 6)
for i in b:
    print(i)

原 array：
[[5. 1. 1. 0. 2. 6.]
 [3. 3. 5. 2. 4. 3.]]
拆分后：
[[5.]
 [3.]]
[[1.]
 [3.]]
[[1.]
 [5.]]
[[0.]
 [2.]]
[[2.]
 [4.]]
[[6.]
 [3.]]
